### ISSUE TITLE
When a test fails, json is not generated

### ISSUE THREAD

**Issue by pmestrum** [Marketionist/protractor-cucumber-steps#52] opened 2018-02-07 15:43 UTC
When Then(/^URL should match \/([^"]*)\/$/ fails, it throws an error in the callback of the then function, which results in an error in the console, and an empty json file.  When I create a similar step myself, without a promise and also throwing an error, it works.

I changed the implementation in a way that the new Error is returned using the callback, instead of throwing it, and now it works.  

I assume that since I use the latest version of cucumber, it's broken.  Can you confirm?

My versions:
    "@ angular/cli": "^1.6.7",
    "@ angular/compiler-cli": "^5.2.3",
    "@ angular/language-service": "^5.2.3",
    "@ angular/service-worker": "^5.2.3",
    "@ compodoc/compodoc": "^1.0.5",
    "@ types/chai": "^4.1.2",
    "@ types/cucumber": "^4.0.0",
    "@ types/jasmine": "~2.8.6",
    "@ types/jasminewd2": "~2.0.3",
    "@ types/node": "~9.4.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "cucumber": "^4.0.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.0",
    "protractor-cucumber-framework": "^4.2.0",
    "protractor-cucumber-steps": "^1.2.0",
    "typescript": "^2.7.1"

New implementation:

    Then(/^URL should match \/([^"]*)\/$/, function (regexp, callback) {
        browser.getCurrentUrl().then(function (url) {
            if (new RegExp(regexp).test(url)) {
                callback();
            } else {
                callback(new Error(`"${url}" ${errors.REGEXP} /${regexp}/`));
            }
        });
    });

Error when working with old code:

    (node:44415) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please 
    require/import the individual methods instead.
    [16:37:04] E/launcher - "http://localhost:4200/policy" does not match provided regexp /\/polixxxcy$/
    [16:37:04] E/launcher - Error: "http://localhost:4200/policy" does not match provided regexp 
    /\/polixxxcy$/
    at node_modules/protractor-cucumber-steps/index.js:649:23
    at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ ode_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    [16:37:04] E/launcher - Process exited with error code 199

**Comment by Marketionist** [comment] 2018-04-06 00:17
@pmestrum thanks for the issue. I tested it with `"cucumber": "^4.1.0",` - looks ok. Maybe the problem is because of the reporter (I use `"cucumber-pretty": "1.4.1",`). Anyway, I plan to update the steps to throw error inside callback as you suggested and also will bump dependencies to the fresh ones.

Also, you are welcome to create PR with fixes if you want. Cheers!

**Comment by Marketionist** [comment] 2018-04-09 11:30
@pmestrum `1.3.0` version of `protractor-cucumber-steps` was released with all mentioned fixes

**Closed as completed by Marketionist** 2018-04-09 11:30 UTC

**Comment by pmestrum** [comment] 2018-04-09 12:35
Hi Dmytro,

Thanks for the update.  I’m currently on another project, but will switch back next week.  I’ll have a look then.

Keep up the good work !

Paul
